kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "cd ../../backend && php artisan serve --host=0.0.0.0 --port=$PORT"

[services.production]

[services.production.build]
args = ["true"]

[services.production.run]
args = ["php", "../../backend/artisan", "serve", "--host=0.0.0.0", "--port=8080"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/v1/health"
